[v1]
"solana-bench-exchange 0.14.2 (path+file:///home/ben/Downloads/solana-0.14.2/bench-exchange)" = ["solana-bench-exchange"]
"solana-bench-streamer 0.14.2 (path+file:///home/ben/Downloads/solana-0.14.2/bench-streamer)" = ["solana-bench-streamer"]
"solana-bench-tps 0.14.2 (path+file:///home/ben/Downloads/solana-0.14.2/bench-tps)" = ["solana-bench-tps"]
"solana-drone 0.14.2 (path+file:///home/ben/Downloads/solana-0.14.2/drone)" = ["solana-drone"]
"solana-fullnode 0.14.2 (path+file:///home/ben/Downloads/solana-0.14.2/fullnode)" = ["solana-fullnode"]
"solana-genesis 0.14.2 (path+file:///home/ben/Downloads/solana-0.14.2/genesis)" = ["solana-genesis"]
"solana-gossip 0.14.2 (path+file:///home/ben/Downloads/solana-0.14.2/gossip)" = ["solana-gossip"]
"solana-install 0.14.2 (path+file:///home/ben/Downloads/solana-0.14.2/install)" = ["solana-install"]
"solana-keygen 0.14.2 (path+file:///home/ben/Downloads/solana-0.14.2/keygen)" = ["solana-keygen"]
"solana-ledger-tool 0.14.0 (path+file:///home/ben/Downloads/solana-0.14.2/ledger-tool)" = ["solana-ledger-tool"]
"solana-wallet 0.14.2 (path+file:///home/ben/Downloads/solana-0.14.2/wallet)" = ["solana-wallet"]
