[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-wallet"
description = "Blockchain, Rebuilt for Scale"
version = "0.14.2"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
bincode = "1.1.3"
bs58 = "0.2.0"
clap = "2.33.0"
chrono = { version = "0.4.0", features = ["serde"] }
dirs = "1.0.5"
log = "0.4.2"
num-traits = "0.2"
serde_json = "1.0.39"
solana-budget-api = { path = "../programs/budget_api", version = "0.14.2"   }
solana-client = { path = "../client", version = "0.14.2"   }
solana-drone = { path = "../drone", version = "0.14.2"   }
solana-logger = { path = "../logger", version = "0.14.2"   }
solana-netutil = { path = "../netutil", version = "0.14.2"   }
solana-sdk = { path = "../sdk", version = "0.14.2"   }
solana-vote-api = { path = "../programs/vote_api", version = "0.14.2"   }
solana-vote-signer = { path = "../vote-signer", version = "0.14.2"   }

[dev-dependencies]
solana-budget-program = { path = "../programs/budget_program", version = "0.14.2"   }
solana = { path = "../core", version = "0.14.2"   }

[features]
cuda = []
erasure = []
