[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-gossip"
description = "Blockchain, Rebuilt for Scale"
version = "0.14.2"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
clap = "2.33.0"
env_logger = "0.6.1"
solana = { path = "../core", version = "0.14.2"   }
solana-client = { path = "../client", version = "0.14.2"    }
solana-netutil = { path = "../netutil", version = "0.14.2"   }
solana-sdk = { path = "../sdk", version = "0.14.2"   }

[features]
chacha = []
cuda = []
erasure = []
