[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-fullnode"
description = "Blockchain, Rebuilt for Scale"
version = "0.14.2"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
clap = "2.33.0"
log = "0.4.2"
serde_json = "1.0.39"
solana = { path = "../core", version = "0.14.2"   }
solana-drone = { path = "../drone", version = "0.14.2"   }
solana-logger = { path = "../logger", version = "0.14.2"   }
solana-netutil = { path = "../netutil", version = "0.14.2"   }
solana-metrics = { path = "../metrics", version = "0.14.2"   }
solana-runtime = { path = "../runtime", version = "0.14.2"   }
solana-sdk = { path = "../sdk", version = "0.14.2"   }
solana-vote-api = { path = "../programs/vote_api", version = "0.14.2"   }
solana-vote-signer = { path = "../vote-signer", version = "0.14.2"   }

[features]
chacha = ["solana/chacha"]
cuda = ["solana/cuda"]
erasure = ["solana/erasure"]
